# Generated by Django 5.0.6 on 2024-06-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_maleclothes_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maleclothes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/male_clothes/'),
        ),
    ]
